# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 195b3ba3dce630b61099f08d3e47c08796a3862551d5937fb0e92480f535fc34c366a7fa08c78d32b23f9bbf48ac8e9e6658c00103d7767cee9d82da306dece5

test:
  secret_key_base: 0367649d2081cc98194505707748b70bd72c1ef44876e862ea0c74a6ae39a3e99797b96ac713a3fd125b87597169b6f0a7db2f9139efaf99a188fe7904d53d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
